### ISSUE TITLE
Setting another profile for IEModeExpiryFix

### ISSUE THREAD

**Issue by leoellis1991** [LesFerch/IEModeExpiryFix#3]
Hello LesFerch Is there a possible way to have my users logged in and use their nonlocal profile and still use the script if so, how do I do that or can I edit the script so I can point it to the profile that they will use on Edge?

**Comment by LesFerch** [comment]
By "nonlocal profile" are you talking about their Edge profile (i.e. sync
is on) or their Windows profile (i.e. roaming profile)?

Please note that the script will not work with Edge profiles that are
synced. With a synced profile, the changes made by the script are
immediately overwritten when Edge starts up.

If your users don't have synced Edge profiles, but do have roaming Windows
profiles, the script should only have to be run once for each user. In that
case, you'll probably want to run the script in console mode. You can run
the VBScript version via CScript.exe or run the PowerShell version.

**Comment by leoellis1991** [comment]
Is it possible to edit this script to use on Synced Edge profiles? 

I also do know that there is another script that goes with that is it possible to edit either one of them to make this work?

**Comment by LesFerch** [comment]
I've spent many hours looking for a way to make the script work with synced
profiles. The problem is not the script. It correctly updates the local
copy of the synced profile, but as soon as Edge is launched, Edge
overwrites the local profile with the copy from the cloud, even though the
local copy is newer. I could not find a way to force Edge to keep the
edited local profile and sync that back to the cloud. The profile is an XML
file, so the base format is the same whether you're looking at Edge or
Chrome, but I researched both browsers and could find no setting that could
be inserted into the XML file to tell the browser to prefer the edited file.

If you research this topic and figure out a solution, that would be
amazing. As it stands, synced profiles cannot be supported.

Please consider alternative solutions, such as using a centrally managed
sitelist (if your users are in AD) or by creating a simple IE launcher
script for those sites that must be run in IE. See the ReadMe
<https://lesferch.github.io/IEModeExpiryFix/> for more details.
