### ISSUE TITLE
The value must be greater than or equal to zero and less than the console's buffer size in that dimension

### ISSUE THREAD

**Issue by bradhs** [LesFerch/IEModeExpiryFix#8]
Has anyone run into this problem?  I haven't spent any time debugging it. Figured I would post it here to see if anyone has dealt with it already.

Set Microsoft Edge Expiry for specific URLs
Exception calling "SetCursorPosition" with "2" argument(s): "The value must be greater than or equal to zero and less 
than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1."
At C:\temp\IEModeExpiryFix.ps1:77 char:5
+     [Console]::SetCursorPosition(0,($CurrentLine - $i))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
Exception calling "SetCursorPosition" with "2" argument(s): "The value must be greater than or equal to zero and less 
than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2."
At C:\temp\IEModeExpiryFix.ps1:77 char:5
+     [Console]::SetCursorPosition(0,($CurrentLine - $i))
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
Exception calling "SetCursorPosition" with "2" argument(s): "The value must be greater than or equal to zero and less 
than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2."
At C:\temp\IEModeExpiryFix.ps1:80 char:3
+   [Console]::SetCursorPosition(0,($CurrentLine - $Count))
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

**Comment by LesFerch** [comment]
I've never seen this issue before. Fortunately, that code is completely optional. It just clears the previous prompt from the display. Try commenting out line 106 (`#If (-Not $Silent) {Clear-Lines 2}`) and then test again.

My first thought for cause of problem is that you're running in `ConstrainedLanguage` mode, but then you would have received an error message to that effect. I should add a check for ConstrainedLanguage anyhow, since the script won't work in that mode.

I also tested with PowerShell Core and found that there was no error, but the script did not find any Edge profiles. I suppose I should add a check for PowerShell Core as well.

For some reason, `$CurrentLine` is zero at that point, causing `SetPosition` to get a `-1` value. That's unexpected. Is there anything unusual about your PowerShell console set up?

**Comment by bradhs** [comment]
I spent a little more time on the script.  I see the issue and have fixed it.  I made a simple change and broke it by skipping over the prompts without using -silent.
